### PR TITLE
Add Django 1.9 Compatibility

### PR DESCRIPTION
**Pull request by impala2**
Some new changes in Django 1.9 prevent the plugin from working as is. Made the required changes and made sure current tests pass.

Had to bump up the CMS version to 3.2 since 3.1 doesn't support Django 1.9.

---

Specifically, these errors are fixed:

    cmsplugin_filer_file.FilerFile.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.
    cmsplugin_filer_link.FilerLinkPlugin.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.

### CODE REVIEW

**Comment by stefanfoulis** [comment]
Thanks @impala2 !
I like ``source`` much better than ``file``, but we need to evaluate the implications for existing projects before changing this.

- do users who are overriding the template need to change anything?
- are there other cases where 3rd party software relies on ``file`` being there?

Might it be an option to set ``related_name ='+'`` instead of renaming the field?

**Comment by impala2** [comment]
@stefanfoulis I merely copied the fix over from here: https://github.com/divio/djangocms-file/pull/13

I tried the `related_name` fix and it doesn't seem to work. Anyone overriding the templates should have no issues as long as they're using the provided methods (`get_file_name()` and such). A possible solution is to have `file` and `file_id` properties that emit deprecation warnings when accessed - I just tested it and and all tests pass.

**Comment by yakky** [comment]
@impala2 I like the deprecation thing. Changing the field names is always painful: even if a clean API exists, I guess that most code still rely on the field name

**Comment by stefanfoulis** [comment]
I have to admin, I'm still not understand quite why this error occurs in the first place.

So our plugin has a model field called ``file``. But what is the ``file`` attribute on ``cms.cmsplugin``?

Is it maybe the automatically generated relation to the plugin model of ``djangocms_file.file`` (https://github.com/divio/djangocms-file/blob/master/djangocms_file/models.py#L22) due to multi-table inheritance?
If so, there is a deeper problem in how all the plugins work, which needs to be solved in django-cms itself. That would mean that if someone releases a new cms plugin called ``Source``, things would break again. And we'll be in a constant dance to try to avoid any such clashes.

@yakky do you think we could fix that in django-cms itself somehow? E.g fix the relationship to have a prefix of the appname (``cmsplgauto_djangocms_file_file`` instead of just ``file``).

**Comment by yakky** [comment]
This looks more related to the ORM than to the CMS itself

**Comment by czpython** [comment]
@stefanfoulis this is the same issue outlined in http://stackoverflow.com/questions/20334029/django-app-cannot-assign-imagetext-link-must-be-a-link-instance/20346355#20346355 and discussed in https://github.com/divio/django-cms/issues/3204. In the end it's a matter of properly naming the models and the fields.

So far all plugins, I prefix the fields with the model name to avoid any kind of clash.

**Comment by stefanfoulis** [comment]
I've created an issue on django-cms for this: https://github.com/divio/django-cms/issues/5030

**Comment by stefanfoulis** [comment]
@impala2 now I realise, the ``related_name = '+'`` can't work, because the one causing the conflict is actually ``djangocms-file``. So I created this pull-request: https://github.com/divio/djangocms-file/pull/17

I'm closing this pull request in favour of fixing the "bug" in ``djangocms-file``, since I suspect many other plugins to have the same problem. After all it is quite likely someone would create a field named ``file``.

**Comment by stefanfoulis** [comment]
An update: keep an eye on divio/django-cms#5032 . We plan to fix this issue in django-cms itself.

**Pull request closed without merging**
